version: '3'

services:
  rabbitmq1:
    image: rabbitmq:3.12.6-management
    restart: on-failure
    container_name: rabbitmq1
    hostname: rabbitmq1
    environment:
      - RABBITMQ_ERLANG_COOKIE=Ra1234567890
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    networks:
      - rabbitmq-network
    volumes:
      - type: bind
        source: ./defaults.conf
        target: /etc/rabbitmq/conf.d/defaults.conf

  rabbitmq2:
    image: rabbitmq:3.12.6-management
    restart: on-failure
    container_name: rabbitmq2
    hostname: rabbitmq2
    environment:
      - RABBITMQ_ERLANG_COOKIE=Ra1234567890
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    networks:
      - rabbitmq-network
    depends_on:
      - rabbitmq1
    volumes:
      - type: bind
        source: ./defaults.conf
        target: /etc/rabbitmq/conf.d/defaults.conf

  rabbitmq3:
    image: rabbitmq:3.12.6-management
    restart: on-failure
    container_name: rabbitmq3
    hostname: rabbitmq3
    environment:
      - RABBITMQ_ERLANG_COOKIE=Ra1234567890
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    networks:
      - rabbitmq-network
    volumes:
      - type: bind
        source: ./defaults.conf
        target: /etc/rabbitmq/conf.d/defaults.conf
    depends_on:
      - rabbitmq1
  haproxy:
    image: haproxy:1.7
    volumes:
      - ./haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro
    depends_on:
      - rabbitmq1
      - rabbitmq2
      - rabbitmq3
    networks:
      - rabbitmq-network
    ports:
      - 15672:15672
      - 5672:5672

networks:
  rabbitmq-network:
    driver: bridge
